%   Plotting script.
%
%   This script uses the variable called answ generated by the script
%   called grid_search_q2a.m. Which is also available from the saved matlab
%   workspace called grid_search.mat
%
%   By pursumation, I think treating the space coordinator as a vector,
%   each space coordinator both will be different in x and y, and it is 
%   will very like the size of the vector which is sqrt(x^2+y^2) 
%   is also different.
%
%   The plot has successfully took the final answ into 3 aprt.

answ_val = zeros(size(answ));
size_temp = size(answ);
for t = 1:size_temp(1)*size_temp(2)
    point = answ{t};
    
    if ~isnan(point)
        val = point*point';
        answ_val(t) = val;
    else
        answ_val(t) = nan;
    end
end
        
plot3(x_mesh,y_mesh,answ_val,'*');    

temp1 = find(answ_val>1.5*10^5);
case1 = cell2mat(answ(temp1));
case1_mean = mean(case1);

temp2 = find(answ_val>7*10^4&answ_val<1.5*10^5);
case2 = cell2mat(answ(temp2));
case2_mean = mean(case2);

temp3 = find(answ_val<7*10^4);
case3 = cell2mat(answ(temp3));
case3_mean = mean(case3);






            


 

        
    
    


